### ISSUE TITLE
Editing "Name Associated" in Appearance tab causes crash

### ISSUE THREAD

**Issue by DotsSalchow** [Lacro59/playnite-librarymanagement-plugin#17]
For some reason, the latest update reset all the "Name Associated" data in the Appearance tab. I had it changed some time before so there wouldn't be duplicate icons for different multiplayer modes, so now I have to change them all over again. Only this time when I try to edit the Names Associated, it causes Playnite to crash. (Deleting the names doesn't result in a crash)

[LibraryManagement_log.zip](https://github.com/Lacro59/playnite-librarymanagement-plugin/files/7446515/LibraryManagement_log.zip)

**Comment by SlipperyJim** [comment]
Can confirm that the same happens for me.
