### ISSUE TITLE
Error on auto and normal update

### ISSUE THREAD

**Issue by Andei** [Lacro59/playnite-librarymanagement-plugin#31]
`28-11 22:37:24.669|ERROR|LibraryManagement#Common:Error on AutoUpdate()|D:\GitHub\Lacro59\playnite-librarymanagement-plugin\source\LibraryManagement.cs|296
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: source
   bei System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   bei LandingPage.ViewModels.LandingPageViewModel.IsRelevantUpdate(ItemUpdateEvent`1 update) in D:\Programmierung\playnite-dev\LandingPage\source\ViewModels\LandingPageViewModel.cs:Zeile 493.
   bei LandingPage.ViewModels.LandingPageViewModel.<>c.<Games_ItemUpdated>b__73_0(ItemUpdateEvent`1 u) in D:\Programmierung\playnite-dev\LandingPage\source\ViewModels\LandingPageViewModel.cs:Zeile 474.
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   bei LandingPage.ViewModels.LandingPageViewModel.Games_ItemUpdated(Object sender, ItemUpdatedEventArgs`1 e) in D:\Programmierung\playnite-dev\LandingPage\source\ViewModels\LandingPageViewModel.cs:Zeile 474.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei Playnite.Database.ItemCollection`1.OnItemUpdated(IEnumerable`1 updates) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:Zeile 598.
   bei Playnite.Database.ItemCollection`1.Update(TItem itemToUpdate) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:Zeile 491.
   bei Playnite.Database.GamesCollection.Update(Game itemToUpdate) in C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:Zeile 167.
   bei LibraryManagement.Services.LibraryManagementTools.<>c__DisplayClass20_0.<UpdateCompanies>b__0() in D:\GitHub\Lacro59\playnite-librarymanagement-plugin\source\Services\LibraryManagementTools.cs:Zeile 761.
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Window.ShowHelper(Object booleanBox)
   bei System.Windows.Window.Show()
   bei System.Windows.Window.ShowDialog()
   bei Playnite.Windows.WindowFactory.<>c__DisplayClass13_0.<CreateAndOpenDialog>b__0(Object a) in C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:Zeile 78.
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei System.Windows.Threading.DispatcherSynchronizationContext.Send(SendOrPostCallback d, Object state)
   bei Playnite.Windows.WindowFactory.CreateAndOpenDialog(Object dataContext) in C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:Zeile 57.
   bei Playnite.ViewModels.ProgressViewViewModel.ActivateProgress() in C:\projects\playnite\source\Playnite\ViewModels\ProgressViewViewModel.cs:Zeile 133.
   bei Playnite.ViewModels.GlobalProgress.ActivateProgress(Action`1 progresAction, GlobalProgressOptions progressArgs) in C:\projects\playnite\source\Playnite\ViewModels\ProgressViewViewModel.cs:Zeile 143.
   bei Playnite.DesktopApp.DesktopDialogs.<>c__DisplayClass24_0.<ActivateGlobalProgress>b__0() in C:\projects\playnite\source\Playnite.DesktopApp\DesktopDialogs.cs:Zeile 170.
   bei Playnite.DesktopApp.DesktopDialogs.<>c__DisplayClass2_0`1.<Invoke>b__0(Object a) in C:\projects\playnite\source\Playnite.DesktopApp\DesktopDialogs.cs:Zeile 32.
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei System.Windows.Threading.DispatcherSynchronizationContext.Send(SendOrPostCallback d, Object state)
   bei Playnite.DesktopApp.DesktopDialogs.Invoke[T](Func`1 action) in C:\projects\playnite\source\Playnite.DesktopApp\DesktopDialogs.cs:Zeile 30.
   bei Playnite.DesktopApp.DesktopDialogs.ActivateGlobalProgress(Action`1 progresAction, GlobalProgressOptions progressArgs) in C:\projects\playnite\source\Playnite.DesktopApp\DesktopDialogs.cs:Zeile 170.
   bei LibraryManagement.Services.LibraryManagementTools.SetCompanies(Boolean OnlyToDay, Game gameUpdated) in D:\GitHub\Lacro59\playnite-librarymanagement-plugin\source\Services\LibraryManagementTools.cs:Zeile 586.
   bei LibraryManagement.LibraryManagement.AutoUpdate(Boolean OnlyToDay, Game gameUpdated) in D:\GitHub\Lacro59\playnite-librarymanagement-plugin\source\LibraryManagement.cs:Zeile 296.
28-11 22:37:25.634|INFO |LibraryManagement#LibraryManagementTools:Task SetGenres() - 00:00.92 for 58/58 items`

**Comment by Lacro59** [comment]
Are you using StartPage plugin?

**Comment by Andei** [comment]
Yes.

**Comment by Lacro59** [comment]
Do you have still this issue after the last update from StartPage?

**Comment by Andei** [comment]
I had it turned off since then, but just checked again - now there are no more problems
