### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by chocolatechipcats** [Lacro59/playnite-librarymanagement-plugin#52]
There's a missing text on what seems to be 'set tags to categories':

![2022-12-22 16_27_12-Add-ons…](https://user-images.githubusercontent.com/47759676/209220541-a5bb3b8b-4012-4f4a-8826-8d14c6384d0c.png)
![2022-12-22 16_28_30-Playnite](https://user-images.githubusercontent.com/47759676/209220543-4536b13b-d369-43ca-b333-a81c80333868.png)

Thank you.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-librarymanagement-plugin/commit/d6a1785f2432b372bc87250fd4f4088917ad4a97
