### ISSUE TITLE
Error in Control name in documentation

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-librarymanagement-plugin#6]
In https://github.com/Lacro59/playnite-librarymanagement-plugin/wiki/Addition-in-a-custom-theme#features-icons-list-supporting-the-different-options-in-the-plugin-settings

It says the name is `LibraryManagement_LmFeaturesIconList"` but it doesn't work.

It should be `LibraryManagement_PluginFeaturesIconList` for it to work

**Comment by Lacro59** [comment]
fixed, thanks
