### ISSUE TITLE
Missing heading text for tag to category

### ISSUE THREAD

**Issue by Gerren** [Lacro59/playnite-librarymanagement-plugin#61]
Hi, I'd like to report a missing text for tag to category conversion.

![2023-02-12 08_57_48-Add-ons…](https://user-images.githubusercontent.com/2953438/218299680-b86b148a-f5db-480f-a28a-2c8e47f26e35.png)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-librarymanagement-plugin/commit/e6333d7533cbb4ca55b26c5706d7eb479f2311ce
