### ISSUE TITLE
Metadata reset after restart

### ISSUE THREAD

**Issue by blackxored** [Lacro59/playnite-librarymanagement-plugin#66]
After running “set tags to genres” I can see the changes in the desktop app, however when I switch to full screen or restart Playnite, I no longer see the genres this plugin added. Is this a bug, or just specific to my setup?

EDIT: I’ve been mainly looking at Steam games, of which Alien Isolation is the first I’m supposed to get a Horror genre from the tags. For added context in case is relevant, I’ve tag black list on the integration settings but all tags I’m using in the plugin should be allowed, and as I mentioned it works till restart. I’ve also disabled update on library update with same result.

**Comment by Lacro59** [comment]
#67
